-- AlterTable
ALTER TABLE "transport" ALTER COLUMN "volume_tank" DROP NOT NULL,
ALTER COLUMN "cost_liter" DROP NOT NULL,
ALTER COLUMN "type_tank" DROP NOT NULL,
ALTER COLUMN "slots" DROP NOT NULL,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "seats" DROP NOT NULL;
