name: build
on:
  push:
    branches:
      - main

env:
  SERVER_HOST: 212.193.31.114
  SERVER_USER: root
  SERVER_PATH: /srv/provportal-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest
